# Generated by Django 4.0.4 on 2022-05-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='remark',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
