# Generated by Django 4.0.4 on 2022-05-19 08:07

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_file_file_alter_file_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(upload_to=apps.models.file.nameFile),
        ),
    ]
