# Generated by Django 4.0.4 on 2022-05-20 02:55

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=apps.models.file.nameFile),
        ),
    ]
